api_version: 1.0

cspace:
  - right_shoulder_pitch_joint
  - right_shoulder_roll_joint
  - right_shoulder_yaw_joint
  - right_elbow_joint
  - right_wrist_roll_joint
  - right_wrist_pitch_joint
  - right_wrist_yaw_joint

default_q: [0.7, -0.2, 0.0, -1.6, 0.0, 0.0, 0.0]
acceleration_limits: [12.0, 12.0, 12.0, 12.0, 16.0, 16.0, 16.0]
jerk_limits: [10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0]

cspace_to_urdf_rules:
  - {name: left_hip_roll_joint, rule: fixed, value: 0.0}
  - {name: left_hip_yaw_joint, rule: fixed, value: 0.0}
  - {name: left_hip_pitch_joint, rule: fixed, value: -0.2}
  - {name: left_knee_joint, rule: fixed, value: 0.3}
  - {name: left_foot_pitch_joint, rule: fixed, value: 0.0}
  - {name: left_foot_roll_joint, rule: fixed, value: 0.0}
  - {name: right_hip_roll_joint, rule: fixed, value: 0.0}
  - {name: right_hip_yaw_joint, rule: fixed, value: 0.0}
  - {name: right_hip_pitch_joint, rule: fixed, value: -0.2}
  - {name: right_knee_joint, rule: fixed, value: 0.3}
  - {name: right_foot_pitch_joint, rule: fixed, value: 0.0}
  - {name: right_foot_roll_joint, rule: fixed, value: 0.0}
  - {name: left_shoulder_pitch_joint, rule: fixed, value: 0.7}
  - {name: left_shoulder_roll_joint, rule: fixed, value: 0.2}
  - {name: left_shoulder_yaw_joint, rule: fixed, value: 0.0}
  - {name: left_elbow_joint, rule: fixed, value: -1.6}
  - {name: left_wrist_roll_joint, rule: fixed, value: 0.0}
  - {name: left_wrist_pitch_joint, rule: fixed, value: 0.0}
  - {name: left_wrist_yaw_joint, rule: fixed, value: 0.0}
  - {name: lh_thumb_cmc_yaw, rule: fixed, value: 0.9}
  - {name: lh_thumb_cmc_pitch, rule: fixed, value: 0.0}
  - {name: lh_thumb_ip, rule: fixed, value: 0.0}
  - {name: lh_index_mcp_pitch, rule: fixed, value: 0.05}
  - {name: lh_index_dip, rule: fixed, value: 0.0445}
  - {name: lh_middle_mcp_pitch, rule: fixed, value: 0.05}
  - {name: lh_middle_dip, rule: fixed, value: 0.0445}
  - {name: lh_ring_mcp_pitch, rule: fixed, value: 0.05}
  - {name: lh_ring_dip, rule: fixed, value: 0.0445}
  - {name: lh_pinky_mcp_pitch, rule: fixed, value: 0.05}
  - {name: lh_pinky_dip, rule: fixed, value: 0.0445}
  - {name: rh_thumb_cmc_yaw, rule: fixed, value: 0.9}
  - {name: rh_thumb_cmc_pitch, rule: fixed, value: 0.0}
  - {name: rh_thumb_ip, rule: fixed, value: 0.0}
  - {name: rh_index_mcp_pitch, rule: fixed, value: 0.05}
  - {name: rh_index_dip, rule: fixed, value: 0.0445}
  - {name: rh_middle_mcp_pitch, rule: fixed, value: 0.05}
  - {name: rh_middle_dip, rule: fixed, value: 0.0445}
  - {name: rh_ring_mcp_pitch, rule: fixed, value: 0.05}
  - {name: rh_ring_dip, rule: fixed, value: 0.0445}
  - {name: rh_pinky_mcp_pitch, rule: fixed, value: 0.05}
  - {name: rh_pinky_dip, rule: fixed, value: 0.0445}

collision_spheres:
  - right_shoulder_pitch_link:
      - {center: [0.0, 0.0, 0.0], radius: 0.075}
  - right_shoulder_yaw_link:
      - {center: [0.0, 0.0, -0.06], radius: 0.065}
  - right_elbow_link:
      - {center: [0.0, 0.0, -0.06], radius: 0.060}
  - right_wrist_roll_link:
      - {center: [0.0, 0.0, -0.04], radius: 0.050}
  - right_wrist_yaw_link:
      - {center: [0.0, 0.0, 0.0], radius: 0.045}
