isaac_assets:
  root: ${S4_SCENE_ASSET_ROOT}
  source_root: ${ISAAC_ASSET_ROOT}
  version: "5.1"
  required:
    - Isaac/Environments/Simple_Warehouse/warehouse.usd
    - Isaac/Props/Sektion_Cabinet/sektion_cabinet_instanceable.usd
    - Isaac/Props/YCB/Axis_Aligned/005_tomato_soup_can.usd
    - Isaac/Props/PackingTable/packing_table.usd
    - Isaac/Props/UIElements/frame_prim.usd
    - Isaac/Props/UIElements/arrow_x.usd
    - Isaac/Environments/Simple_Warehouse/Materials/OmniUe4Base.mdl
    - Isaac/Environments/Simple_Warehouse/Materials/OmniUe4Function.mdl
robot:
  root: ${S4_PROJECT_ROOT}/assets/my_robot
  required:
    - urdf/s4_40DOF_fullbody.urdf
base_model:
  root: ${SMOLVLA_MODEL_ROOT}/HuggingFaceTB/SmolVLM2-500M-Video-Instruct
  source: HuggingFaceTB/SmolVLM2-500M-Video-Instruct
external_repositories:
  isaaclab: ${ISAACLAB_ROOT}
  lerobot: ${LEROBOT_ROOT}
